SARnetStatus = [
    {
        "built": true,
        "county": "Broward",
        "duplex": "+",
        "frequency": 442.825,
        "grid_zone": "17R",
        "hundred_km_id": "NJ",
        "last_update": "TIMESTAMP",
        "latitude": 26.14502,
        "longitude": -80.45427,
        "memory_label": "SNJBRO",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Andytown",
        "status": "On-Air",
        "tone_frequency": 110.9,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Franklin",
        "duplex": "+",
        "frequency": 444.4,
        "grid_zone": "16R",
        "hundred_km_id": "FT",
        "last_update": "TIMESTAMP",
        "latitude": 29.9207,
        "longitude": -84.97328,
        "memory_label": "WFTFRA",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Apalachicola",
        "status": "On-Air",
        "tone_frequency": 94.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Hernando",
        "duplex": "+",
        "frequency": 444.825,
        "grid_zone": "17R",
        "hundred_km_id": "LM",
        "last_update": "TIMESTAMP",
        "latitude": 28.55527,
        "longitude": -82.38787,
        "memory_label": "CLMHER",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Brooksville",
        "status": "Off-Air",
        "tone_frequency": 146.2,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Osceola",
        "duplex": "+",
        "frequency": 444.975,
        "grid_zone": "17R",
        "hundred_km_id": "ML",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CMLOSC",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Central Turnpike",
        "status": "On-Air",
        "tone_frequency": 107.2,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Gadsden",
        "duplex": "+",
        "frequency": 444.975,
        "grid_zone": "16R",
        "hundred_km_id": "GU",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WGUGAD",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Chattahoochee",
        "status": "On-Air",
        "tone_frequency": 94.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": false,
        "county": "Levy",
        "duplex": "+",
        "frequency": 0,
        "grid_zone": "17R",
        "hundred_km_id": "LN",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NLNLEV",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Chiefland",
        "status": "Off-Air",
        "tone_frequency": 0,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Washington",
        "duplex": "+",
        "frequency": 444.75,
        "grid_zone": "16R",
        "hundred_km_id": "FV",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WFVWAG",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Chipley",
        "status": "On-Air",
        "tone_frequency": 100,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Lake",
        "duplex": "+",
        "frequency": 444.975,
        "grid_zone": "17R",
        "hundred_km_id": "MM",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CMMLAK",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Clermont",
        "status": "On-Air",
        "tone_frequency": 103.5,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Brevard",
        "duplex": "+",
        "frequency": 444.65,
        "grid_zone": "17R",
        "hundred_km_id": "NM",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CNMBRE",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Cocoa",
        "status": "On-Air",
        "tone_frequency": 107.2,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Okaloosa",
        "duplex": "+",
        "frequency": 444.9,
        "grid_zone": "16R",
        "hundred_km_id": "EV",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WEVOKA",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Crestview",
        "status": "On-Air",
        "tone_frequency": 100,
        "type": "Repeater (FB2)"
    },
    {
        "built": false,
        "county": "Volusia",
        "duplex": "+",
        "frequency": 442.875,
        "grid_zone": "17R",
        "hundred_km_id": "MN",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NMNVOL",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Daytona",
        "status": "Off-Air",
        "tone_frequency": 123,
        "type": "Control Station (FX1)"
    },
    {
        "built": false,
        "county": "Polk",
        "duplex": "+",
        "frequency": 444.35,
        "grid_zone": "17R",
        "hundred_km_id": "ML",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CMLPOL",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Dundee",
        "status": "Off-Air",
        "tone_frequency": 103.5,
        "type": "Repeater (FB2)"
    },
    {
        "built": false,
        "county": "Lee",
        "duplex": "+",
        "frequency": 0,
        "grid_zone": "17R",
        "hundred_km_id": "MK",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "SMKLEE",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Estero",
        "status": "On-Air",
        "tone_frequency": 0,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Broward",
        "duplex": "+",
        "frequency": 442.85,
        "grid_zone": "17R",
        "hundred_km_id": "NJ",
        "last_update": "TIMESTAMP",
        "latitude": 26.256472923285344,
        "longitude": -80.25512695312501,
        "memory_label": "SNJBRO",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Ft. Lauderdale",
        "status": "On-Air",
        "tone_frequency": 110.9,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Miami-Dade",
        "duplex": "+",
        "frequency": 442.05,
        "grid_zone": "17R",
        "hundred_km_id": "NJ",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "SNJDAD",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Florida City",
        "status": "On-Air",
        "tone_frequency": 114.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Lee",
        "duplex": "+",
        "frequency": 444.225,
        "grid_zone": "17R",
        "hundred_km_id": "MK",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "SMKLEE",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Ft. Myers",
        "status": "On-Air",
        "tone_frequency": 136.5,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Alachua",
        "duplex": "+",
        "frequency": 444.925,
        "grid_zone": "17R",
        "hundred_km_id": "LN",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NLNALC",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Gainesville",
        "status": "On-Air",
        "tone_frequency": 123,
        "type": "Control Station (FX1)"
    },
    {
        "built": true,
        "county": "Monroe",
        "duplex": "+",
        "frequency": 442.85,
        "grid_zone": "17R",
        "hundred_km_id": "NH",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "KNHMON",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Keys",
        "site_name": "Islamorada",
        "status": "Off-Air",
        "tone_frequency": 114.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Duval",
        "duplex": "+",
        "frequency": 444.7,
        "grid_zone": "17R",
        "hundred_km_id": "MP",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NMPDUV",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Jacksonville",
        "status": "Off-Air",
        "tone_frequency": 127.3,
        "type": "Repeater (FB2)"
    },
    {
        "built": false,
        "county": "Monroe",
        "duplex": "+",
        "frequency": 444.4,
        "grid_zone": "17R",
        "hundred_km_id": "MH",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "KMHMON",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Keys",
        "site_name": "Key West",
        "status": "Off-Air",
        "tone_frequency": 114.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Columbia",
        "duplex": "+",
        "frequency": 444.9,
        "grid_zone": "17R",
        "hundred_km_id": "LP",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NLPCLM",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Lake City",
        "status": "On-Air",
        "tone_frequency": 110.9,
        "type": "Control Station (FX1)"
    },
    {
        "built": true,
        "county": "Polk",
        "duplex": "+",
        "frequency": 442.275,
        "grid_zone": "17R",
        "hundred_km_id": "MM",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CMMPOL",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Lakeland",
        "status": "On-Air",
        "tone_frequency": 82.5,
        "type": "Control Station (FX1)"
    },
    {
        "built": true,
        "county": "Suwannee",
        "duplex": "+",
        "frequency": 443.7,
        "grid_zone": "17R",
        "hundred_km_id": "LP",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NLPSUW",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Live Oak",
        "status": "On-Air",
        "tone_frequency": 110.9,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Madison",
        "duplex": "+",
        "frequency": 444.3,
        "grid_zone": "17R",
        "hundred_km_id": "KP",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NKPMAD",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Madison",
        "status": "On-Air",
        "tone_frequency": 94.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Miami-Dade",
        "duplex": "+",
        "frequency": 444.6,
        "grid_zone": "17R",
        "hundred_km_id": "NJ",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "SNJDAD",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Miami",
        "status": "On-Air",
        "tone_frequency": 167.9,
        "type": "Control Station (FX1)"
    },
    {
        "built": true,
        "county": "Santa Rosa",
        "duplex": "+",
        "frequency": 444.725,
        "grid_zone": "16R",
        "hundred_km_id": "DU",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WDUSAN",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Milton",
        "status": "On-Air",
        "tone_frequency": 100,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Collier",
        "duplex": "+",
        "frequency": 444.95,
        "grid_zone": "17R",
        "hundred_km_id": "MJ",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "SMJCLR",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Naples",
        "status": "On-Air",
        "tone_frequency": 103.5,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Marion",
        "duplex": "+",
        "frequency": 444.025,
        "grid_zone": "17R",
        "hundred_km_id": "LN",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NLNMAO",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Ocala",
        "status": "On-Air",
        "tone_frequency": 123,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Orange",
        "duplex": "+",
        "frequency": 444.075,
        "grid_zone": "17R",
        "hundred_km_id": "MM",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CMMORA",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Orlando",
        "status": "On-Air",
        "tone_frequency": 103.5,
        "type": "Repeater (FB2)"
    },
    {
        "built": false,
        "county": "Palm Beach",
        "duplex": "+",
        "frequency": 0,
        "grid_zone": "17R",
        "hundred_km_id": "NK",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "SNKPAL",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Pahokee",
        "status": "On-Air",
        "tone_frequency": 0,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Palm beach",
        "duplex": "+",
        "frequency": 443.975,
        "grid_zone": "17R",
        "hundred_km_id": "NK ",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "SNKPAL",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "South",
        "site_name": "Palm Beach",
        "status": "On-Air",
        "tone_frequency": 110.9,
        "type": "Control Station (FX1)"
    },
    {
        "built": true,
        "county": "Bay",
        "duplex": "+",
        "frequency": 444.175,
        "grid_zone": "16R",
        "hundred_km_id": "FU",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WFUBAY",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Panama City",
        "status": "On-Air",
        "tone_frequency": 100,
        "type": "Control Station (FX1)"
    },
    {
        "built": false,
        "county": "Escambia",
        "duplex": "+",
        "frequency": 444.875,
        "grid_zone": "16R",
        "hundred_km_id": "DU",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WDUESC",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Pensacola",
        "status": "Off-Air",
        "tone_frequency": 100,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Taylor",
        "duplex": "+",
        "frequency": 443.1,
        "grid_zone": "17R",
        "hundred_km_id": "KP",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NKPTAY",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Perry",
        "status": "On-Air",
        "tone_frequency": 94.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Sarasota",
        "duplex": "+",
        "frequency": 444.8,
        "grid_zone": "17R",
        "hundred_km_id": "LL",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CLLSAR",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Sarasota",
        "status": "Off-Air",
        "tone_frequency": 100,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Brevard",
        "duplex": "+",
        "frequency": 444.375,
        "grid_zone": "17R",
        "hundred_km_id": "NL",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CNLBRE",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Sebastian",
        "status": "On-Air",
        "tone_frequency": 107.2,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Leon",
        "duplex": "+",
        "frequency": 443.5,
        "grid_zone": "16R",
        "hundred_km_id": "GU",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WGULEO",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "State Emergency Operations Center (SEOC)",
        "status": "On-Air",
        "tone_frequency": 94.8,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Pinellas",
        "duplex": "+",
        "frequency": 442.25,
        "grid_zone": "17R",
        "hundred_km_id": "LL",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CLLPIN",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Skyway Bridge",
        "status": "On-Air",
        "tone_frequency": 146.2,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "St. Johns",
        "duplex": "+",
        "frequency": 442.8,
        "grid_zone": "17R",
        "hundred_km_id": "MP",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NMPSTJ",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "St. Augustine",
        "status": "On-Air",
        "tone_frequency": 127.3,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Martin",
        "duplex": "+",
        "frequency": 444.15,
        "grid_zone": "17R",
        "hundred_km_id": "NL",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CNLMRT",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Stuart",
        "status": "On-Air",
        "tone_frequency": 107.2,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Leon",
        "duplex": "+",
        "frequency": 442.1,
        "grid_zone": "16R",
        "hundred_km_id": "GU",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "WGULEO",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "West",
        "site_name": "Tallahassee",
        "status": "On-Air",
        "tone_frequency": 94.8,
        "type": "Control Station (FX1)"
    },
    {
        "built": true,
        "county": "Hillsborough",
        "duplex": "+",
        "frequency": 442.85,
        "grid_zone": "17R ",
        "hundred_km_id": "LL",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "CLLHIL",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "Central",
        "site_name": "Tampa",
        "status": "On-Air",
        "tone_frequency": 146.2,
        "type": "Repeater (FB2)"
    },
    {
        "built": true,
        "county": "Nassau",
        "duplex": "+",
        "frequency": 442.9,
        "grid_zone": "17R",
        "hundred_km_id": "MP",
        "last_update": "TIMESTAMP",
        "latitude": 28,
        "longitude": 84,
        "memory_label": "NMPNAS",
        "notes": "STATUS",
        "offset": 5.000000,
        "region": "North",
        "site_name": "Yulee",
        "status": "On-Air",
        "tone_frequency": 127.3,
        "type": "Repeater (FB2)"
    }
];