SARnetStatus = [
 {
  "built": true,
  "county": "Broward",
  "duplex": "+",
  "frequency": 442.825,
  "grid_zone": "17R",
  "hundred_km_id": "NJ",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 26.14502,
  "longitude": -80.45427,
  "memory_label": "SNJBRO",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "South",
  "site_name": "Andytown",
  "status": "On-Air",
  "tone_frequency": 110.9,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Franklin",
  "duplex": "+",
  "frequency": 444.4,
  "grid_zone": "16R",
  "hundred_km_id": "FT",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WFTFRA",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "West",
  "site_name": "Apalachicola",
  "status": "On-Air",
  "tone_frequency": 94.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Hernando",
  "duplex": "+",
  "frequency": 444.825,
  "grid_zone": "17R",
  "hundred_km_id": "LM",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CLMHER",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Brooksville",
  "status": "On-Air",
  "tone_frequency": 146.2,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Osceola",
  "duplex": "+",
  "frequency": 444.975,
  "grid_zone": "17R",
  "hundred_km_id": "ML",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CMLOSC",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Central Turnpike",
  "status": "On-Air",
  "tone_frequency": 107.2,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Gadsden",
  "duplex": "+",
  "frequency": 444.975,
  "grid_zone": "16R",
  "hundred_km_id": "GU",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WGUGAD",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "West",
  "site_name": "Chattahoochee",
  "status": "On-Air",
  "tone_frequency": 94.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": false,
  "county": "Levy",
  "duplex": "+",
  "frequency": 0,
  "grid_zone": "17R",
  "hundred_km_id": "LN",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NLNLEV",
  "notes": "Site is in planning stage.",
  "offset": 5,
  "region": "North",
  "site_name": "Chiefland",
  "status": "Off-Air",
  "tone_frequency": 0,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Washington",
  "duplex": "+",
  "frequency": 444.75,
  "grid_zone": "16R",
  "hundred_km_id": "FV",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WFVWAG",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "West",
  "site_name": "Chipley",
  "status": "On-Air",
  "tone_frequency": 100,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Lake",
  "duplex": "+",
  "frequency": 444.975,
  "grid_zone": "17R",
  "hundred_km_id": "MM",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CMMLAK",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Clermont",
  "status": "On-Air",
  "tone_frequency": 103.5,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Brevard",
  "duplex": "+",
  "frequency": 444.65,
  "grid_zone": "17R",
  "hundred_km_id": "NM",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CNMBRE",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Cocoa",
  "status": "On-Air",
  "tone_frequency": 107.2,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Okaloosa",
  "duplex": "+",
  "frequency": 444.9,
  "grid_zone": "16R",
  "hundred_km_id": "EV",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WEVOKA",
  "notes": "Site is operational. Frequency will be changed to avoid interference with Alabama site.",
  "offset": 5,
  "region": "West",
  "site_name": "Crestview",
  "status": "On-Air",
  "tone_frequency": 100,
  "type": "Repeater (FB2)"
 },
 {
  "built": false,
  "county": "Volusia",
  "duplex": "+",
  "frequency": 442.875,
  "grid_zone": "17R",
  "hundred_km_id": "MN",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NMNVOL",
  "notes": "Site is pending FDOT approval.",
  "offset": 5,
  "region": "North",
  "site_name": "Daytona",
  "status": "Off-Air",
  "tone_frequency": 123,
  "type": "Control Station (FX1)"
 },
 {
  "built": false,
  "county": "Polk",
  "duplex": "+",
  "frequency": 444.35,
  "grid_zone": "17R",
  "hundred_km_id": "ML",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CMLPOL",
  "notes": "Frequency has been selected. Site is in planning stages.",
  "offset": 5,
  "region": "Central",
  "site_name": "Dundee",
  "status": "Off-Air",
  "tone_frequency": 103.5,
  "type": "Repeater (FB2)"
 },
 {
  "built": false,
  "county": "Lee",
  "duplex": "+",
  "frequency": 0,
  "grid_zone": "17R",
  "hundred_km_id": "MK",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SMKLEE",
  "notes": "Site is pending FDOT approval.",
  "offset": 5,
  "region": "South",
  "site_name": "Estero",
  "status": "Off-Air",
  "tone_frequency": 0,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Broward",
  "duplex": "+",
  "frequency": 442.85,
  "grid_zone": "17R",
  "hundred_km_id": "NJ",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SNJBRO",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "South",
  "site_name": "Ft. Lauderdale",
  "status": "On-Air",
  "tone_frequency": 110.9,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Miami-Dade",
  "duplex": "+",
  "frequency": 442.05,
  "grid_zone": "17R",
  "hundred_km_id": "NJ",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SNJDAD",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "South",
  "site_name": "Florida City",
  "status": "On-Air",
  "tone_frequency": 114.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Lee",
  "duplex": "+",
  "frequency": 444.225,
  "grid_zone": "17R",
  "hundred_km_id": "MK",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SMKLEE",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "South",
  "site_name": "Ft. Myers",
  "status": "On-Air",
  "tone_frequency": 136.5,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Alachua",
  "duplex": "+",
  "frequency": 444.925,
  "grid_zone": "17R",
  "hundred_km_id": "LN",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NLNALC",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "Gainesville",
  "status": "On-Air",
  "tone_frequency": 123,
  "type": "Control Station (FX1)"
 },
 {
  "built": true,
  "county": "Monroe",
  "duplex": "+",
  "frequency": 442.85,
  "grid_zone": "17R",
  "hundred_km_id": "NH",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "KNHMON",
  "notes": "Site is off-line.",
  "offset": 5,
  "region": "Keys",
  "site_name": "Islamorada",
  "status": "Off-Air",
  "tone_frequency": 114.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Duval",
  "duplex": "+",
  "frequency": 444.7,
  "grid_zone": "17R",
  "hundred_km_id": "MP",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NMPDUV",
  "notes": "Site is operational",
  "offset": 5,
  "region": "North",
  "site_name": "Jacksonville",
  "status": "On-Air",
  "tone_frequency": 127.3,
  "type": "Repeater (FB2)"
 },
 {
  "built": false,
  "county": "Monroe",
  "duplex": "+",
  "frequency": 444.4,
  "grid_zone": "17R",
  "hundred_km_id": "MH",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "KMHMON",
  "notes": "Formerly Sugarloaf. Site is in planning stage.",
  "offset": 5,
  "region": "Keys",
  "site_name": "Key West",
  "status": "Off-Air",
  "tone_frequency": 114.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Columbia",
  "duplex": "+",
  "frequency": 444.9,
  "grid_zone": "17R",
  "hundred_km_id": "LP",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NLPCLM",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "Lake City",
  "status": "On-Air",
  "tone_frequency": 110.9,
  "type": "Control Station (FX1)"
 },
 {
  "built": true,
  "county": "Polk",
  "duplex": "+",
  "frequency": 442.275,
  "grid_zone": "17R",
  "hundred_km_id": "MM",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CMMPOL",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Lakeland",
  "status": "On-Air",
  "tone_frequency": 82.5,
  "type": "Control Station (FX1)"
 },
 {
  "built": true,
  "county": "Suwannee",
  "duplex": "+",
  "frequency": 443.7,
  "grid_zone": "17R",
  "hundred_km_id": "LP",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NLPSUW",
  "notes": "Live Oak is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "Live Oak",
  "status": "Off-Air",
  "tone_frequency": 110.9,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Madison",
  "duplex": "+",
  "frequency": 444.3,
  "grid_zone": "17R",
  "hundred_km_id": "KP",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NKPMAD",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "Madison",
  "status": "On-Air",
  "tone_frequency": 94.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Miami-Dade",
  "duplex": "+",
  "frequency": 444.6,
  "grid_zone": "17R",
  "hundred_km_id": "NJ",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SNJDAD",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "South",
  "site_name": "Miami",
  "status": "On-Air",
  "tone_frequency": 167.9,
  "type": "Control Station (FX1)"
 },
 {
  "built": true,
  "county": "Santa Rosa",
  "duplex": "+",
  "frequency": 444.725,
  "grid_zone": "16R",
  "hundred_km_id": "DU",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WDUSAN",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "West",
  "site_name": "Milton",
  "status": "On-Air",
  "tone_frequency": 100,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Collier",
  "duplex": "+",
  "frequency": 444.95,
  "grid_zone": "17R",
  "hundred_km_id": "MJ",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SMJCLR",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "South",
  "site_name": "Naples",
  "status": "On-Air",
  "tone_frequency": 103.5,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Marion",
  "duplex": "+",
  "frequency": 444.025,
  "grid_zone": "17R",
  "hundred_km_id": "LN",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NLNMAO",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "Ocala",
  "status": "On-Air",
  "tone_frequency": 123,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Orange",
  "duplex": "+",
  "frequency": 444.075,
  "grid_zone": "17R",
  "hundred_km_id": "MM",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CMMORA",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Orlando",
  "status": "On-Air",
  "tone_frequency": 103.5,
  "type": "Repeater (FB2)"
 },
 {
  "built": false,
  "county": "Palm Beach",
  "duplex": "+",
  "frequency": 0,
  "grid_zone": "17R",
  "hundred_km_id": "NK",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SNKPAL",
  "notes": "Site is in planning stage.",
  "offset": 5,
  "region": "South",
  "site_name": "Pahokee",
  "status": "Off-Air",
  "tone_frequency": 0,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Palm beach",
  "duplex": "+",
  "frequency": 443.975,
  "grid_zone": "17R",
  "hundred_km_id": "NK ",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "SNKPAL",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "South",
  "site_name": "Palm Beach",
  "status": "On-Air",
  "tone_frequency": 110.9,
  "type": "Control Station (FX1)"
 },
 {
  "built": true,
  "county": "Bay",
  "duplex": "+",
  "frequency": 444.175,
  "grid_zone": "16R",
  "hundred_km_id": "FU",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WFUBAY",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "West",
  "site_name": "Panama City",
  "status": "On-Air",
  "tone_frequency": 100,
  "type": "Control Station (FX1)"
 },
 {
  "built": false,
  "county": "Escambia",
  "duplex": "+",
  "frequency": 444.875,
  "grid_zone": "16R",
  "hundred_km_id": "DU",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WDUESC",
  "notes": "Frequency selected. Site is in planning stage.",
  "offset": 5,
  "region": "West",
  "site_name": "Pensacola",
  "status": "Off-Air",
  "tone_frequency": 100,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Taylor",
  "duplex": "+",
  "frequency": 443.1,
  "grid_zone": "17R",
  "hundred_km_id": "KP",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NKPTAY",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "Perry",
  "status": "On-Air",
  "tone_frequency": 94.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Sarasota",
  "duplex": "+",
  "frequency": 444.8,
  "grid_zone": "17R",
  "hundred_km_id": "LL",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CLLSAR",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Sarasota",
  "status": "On-Air",
  "tone_frequency": 100,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Brevard",
  "duplex": "+",
  "frequency": 444.375,
  "grid_zone": "17R",
  "hundred_km_id": "NL",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CNLBRE",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Sebastian",
  "status": "On-Air",
  "tone_frequency": 107.2,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Leon",
  "duplex": "+",
  "frequency": 443.5,
  "grid_zone": "16R",
  "hundred_km_id": "GU",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WGULEO",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "West",
  "site_name": "State Emergency Operations Center (SEOC)",
  "status": "On-Air",
  "tone_frequency": 94.8,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Pinellas",
  "duplex": "+",
  "frequency": 442.25,
  "grid_zone": "17R",
  "hundred_km_id": "LL",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CLLPIN",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Skyway Bridge",
  "status": "On-Air",
  "tone_frequency": 146.2,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "St. Johns",
  "duplex": "+",
  "frequency": 442.8,
  "grid_zone": "17R",
  "hundred_km_id": "MP",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NMPSTJ",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "St. Augustine",
  "status": "On-Air",
  "tone_frequency": 127.3,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Martin",
  "duplex": "+",
  "frequency": 444.15,
  "grid_zone": "17R",
  "hundred_km_id": "NL",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CNLMRT",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Stuart",
  "status": "On-Air",
  "tone_frequency": 107.2,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Leon",
  "duplex": "+",
  "frequency": 442.1,
  "grid_zone": "16R",
  "hundred_km_id": "GU",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "WGULEO",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "West",
  "site_name": "Tallahassee",
  "status": "On-Air",
  "tone_frequency": 94.8,
  "type": "Control Station (FX1)"
 },
 {
  "built": true,
  "county": "Hillsborough",
  "duplex": "+",
  "frequency": 442.85,
  "grid_zone": "17R ",
  "hundred_km_id": "LL",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "CLLHIL",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "Central",
  "site_name": "Tampa",
  "status": "On-Air",
  "tone_frequency": 146.2,
  "type": "Repeater (FB2)"
 },
 {
  "built": true,
  "county": "Nassau",
  "duplex": "+",
  "frequency": 442.9,
  "grid_zone": "17R",
  "hundred_km_id": "MP",
  "last_update": "11/16/2020, 5:05:59 PM",
  "latitude": 28,
  "longitude": 84,
  "memory_label": "NMPNAS",
  "notes": "Site is operational.",
  "offset": 5,
  "region": "North",
  "site_name": "Yulee",
  "status": "On-Air",
  "tone_frequency": 127.3,
  "type": "Repeater (FB2)"
 }
];